### ISSUE TITLE
Extract template version information from CosmosDB

### ISSUE THREAD

**Issue by TonyWildish-BH** [Barts-Life-Science/AzureTRE#209]
This is a component of #188, about populating workspace documents in the CosmosDB with template version information.

The foundational component is to be able to interrogate the CosmosDB to retrieve the list of active templates and their version numbers. This can then be used to build the data structure defined in #188. Doing this will probably require:
* A role that can access the CosmosDB with the correct privileges
* Network access to the CosmosDB. Currently, it's completely firewalled off to the outside world, but the SDE can access it from inside it's own vnet. We will probably need to be able to open the firewall for selected IP addresses/ranges for development purposes, and maybe also for production use if we take the 'script' path for the catalogue management work. The DB should not, however, be generally available from the internet.
* A script, preferably written in Python, or Bash if that's not easy.

Acceptance criteria:
- [ ] A mechanism for controlling the network access in a way that won't upset terraform if it notices it (i.e. not provoking terraform to destroy/redeploy the CosmosDB when we refresh the codebase from upstream)
- [ ] A script/tool/terraform module to create the access role. Preferably a terraform module, which can be fed back to the MS repo.
- [ ] A script to extract template information
- [ ] Parsing that information for active templates and their versions
- [ ] Documentation

**Comment by TonyWildish-BH** [comment]
This is being superceded by other tickets.
